version: '3.3'
services:
  dbserver:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: disprueba
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - "c:/disprueba:/var/lib/postgresql/data"
    ports:
      - "5433:5433"
    expose:
      - 5433
  consul:
    image: consul:1.15.4
    command: |
      agent -dev
      -ui
      -bind=0.0.0.0
      -client=0.0.0.0
    ports:
      - "8500:8500"
    expose:
      - 8500
  proxy:
    image: traefik:3.0.4
    command: |
      --api.insecure=true
      --providers.consulCatalog
      --providers.consulCatalog.exposedByDefault=false
      --providers.consulCatalog.endpoint.address=consul:8500
      --providers.consulCatalog.refreshInterval=10s
    ports:
      - "8080:8080"
      - "7070:80"
    expose:
      - 80
    depends_on:
      - consul
  clientes-service:
    image: santiagochango/cliente
    environment:
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://dbserver:5432/disprueba
      QUARKUS_HTTP_PORT: 8080
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
    depends_on:
      - dbserver
      - consul
    deploy:
      replicas: 2
  productos-service:
    image: santiagochango/producto
    environment:
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://dbserver:5432/disprueba
      QUARKUS_HTTP_PORT: 8080
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
    depends_on:
      - dbserver
      - consul
    deploy:
      replicas: 2
  ordenes-service:
    image: santiagochango/orden_compra
    environment:
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://dbserver:5432/disprueba
      QUARKUS_HTTP_PORT: 8080
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
    depends_on:
      - dbserver
      - consul
    deploy:
      replicas: 2
  frontend:
    image: santiagochango/cliente-vue-front
    depends_on:
      - proxy
    ports:
      - "8081:80"
    expose:
      - 8081